// Tauri invoke-handler registry extracted from lib.rs to keep the entrypoint thin.

#[macro_export]
macro_rules! register_tauri_commands {
    () => {
        tauri::generate_handler![
            greet,
            commands::health::health_check,
            commands::task_commands::query::list_tasks,
            commands::task_commands::query::get_task,
            commands::task_commands::mutation::create_task,
            commands::task_commands::mutation::update_task,
            commands::task_commands::mutation::answer_user_question,
            commands::task_commands::mutation::inject_task,
            commands::task_commands::mutation::move_task,
            commands::task_commands::mutation::archive_task,
            commands::task_commands::mutation::restore_task,
            commands::task_commands::mutation::block_task,
            commands::task_commands::mutation::unblock_task,
            commands::task_commands::mutation::cleanup_task,
            commands::task_commands::mutation::cleanup_tasks_in_group,
            commands::task_commands::mutation::cancel_tasks_in_group,
            commands::task_commands::mutation::pause_tasks_in_group,
            commands::task_commands::mutation::resume_tasks_in_group,
            commands::task_commands::mutation::archive_tasks_in_group,
            commands::task_commands::mutation::pause_task,
            commands::task_commands::mutation::resume_task,
            commands::task_commands::mutation::stop_task,
            commands::task_commands::query::get_archived_count,
            commands::task_commands::query::search_tasks,
            commands::task_commands::query::get_valid_transitions,
            commands::task_commands::query::get_tasks_awaiting_review,
            commands::task_commands::query::get_task_state_transitions,
            commands::task_commands::query::get_task_dependency_graph,
            commands::task_commands::query::get_task_timeline_events,
            // Task step commands
            commands::task_step_commands::create_task_step,
            commands::task_step_commands::get_task_steps,
            commands::task_step_commands::update_task_step,
            commands::task_step_commands::reorder_task_steps,
            commands::task_step_commands::get_step_progress,
            commands::task_step_commands::start_step,
            commands::task_step_commands::complete_step,
            commands::task_step_commands::skip_step,
            commands::task_step_commands::fail_step,
            commands::project_commands::list_projects,
            commands::project_commands::get_project,
            commands::project_commands::create_project,
            commands::project_commands::update_project,
            commands::project_commands::archive_project,
            commands::project_commands::get_git_branches,
            commands::project_commands::get_git_current_branch,
            commands::project_commands::get_git_default_branch,
            commands::project_commands::reanalyze_project,
            commands::project_commands::update_custom_analysis,
            commands::project_commands::get_git_remote_url,
            commands::project_commands::check_gh_auth,
            commands::project_commands::update_github_pr_enabled,
            commands::agent_profile_commands::list_agent_profiles,
            commands::agent_profile_commands::get_agent_profile,
            commands::agent_profile_commands::get_agent_profiles_by_role,
            commands::agent_profile_commands::get_builtin_agent_profiles,
            commands::agent_profile_commands::get_custom_agent_profiles,
            commands::agent_profile_commands::seed_builtin_profiles,
            commands::qa_commands::get_qa_settings,
            commands::qa_commands::update_qa_settings,
            commands::qa_commands::get_task_qa,
            commands::qa_commands::get_qa_results,
            commands::qa_commands::retry_qa,
            commands::qa_commands::skip_qa,
            commands::review_commands::get_pending_reviews,
            commands::review_commands::get_review_by_id,
            commands::review_commands::get_reviews_by_task_id,
            commands::review_commands::get_task_state_history,
            commands::review_commands::approve_review,
            commands::review_commands::request_changes,
            commands::review_commands::reject_review,
            commands::review_commands::approve_fix_task,
            commands::review_commands::reject_fix_task,
            commands::review_commands::get_fix_task_attempts,
            commands::review_commands::approve_task_for_review,
            commands::review_commands::request_task_changes_for_review,
            commands::review_commands::request_task_changes_from_reviewing,
            commands::review_commands::re_review_task_from_escalated,
            // Review issue commands
            commands::review_commands::get_task_issues,
            commands::review_commands::get_issue_progress,
            commands::review_commands::verify_issue,
            commands::review_commands::reopen_issue,
            commands::review_commands::mark_issue_in_progress,
            commands::review_commands::mark_issue_addressed,
            // Review settings commands
            commands::review_commands::get_review_settings,
            commands::review_commands::update_review_settings,
            commands::execution_commands::get_execution_status,
            commands::execution_commands::pause_execution,
            commands::execution_commands::resume_execution,
            commands::execution_commands::stop_execution,
            commands::execution_commands::restart_task,
            commands::execution_commands::recover_task_execution,
            commands::execution_commands::resolve_recovery_prompt,
            commands::execution_commands::set_max_concurrent,
            commands::execution_commands::get_execution_settings,
            commands::execution_commands::update_execution_settings,
            commands::execution_commands::set_active_project,
            commands::execution_commands::get_active_project,
            commands::execution_commands::get_global_execution_settings,
            commands::execution_commands::update_global_execution_settings,
            commands::execution_commands::get_running_processes,
            // Merge pipeline commands
            commands::merge_pipeline_commands::get_merge_pipeline,
            commands::merge_pipeline_commands::get_merge_progress,
            commands::merge_pipeline_commands::get_merge_phase_list,
            commands::conversation_stats_commands::get_agent_conversation_stats,
            commands::conversation_stats_commands::get_project_chat_usage_stats,
            commands::conversation_stats_commands::get_task_chat_usage_stats,
            // Metrics commands
            commands::metrics_commands::get_project_stats,
            commands::metrics_commands::get_project_trends,
            commands::metrics_commands::get_metrics_config,
            commands::metrics_commands::save_metrics_config,
            commands::metrics_commands::get_column_metrics,
            commands::metrics_commands::get_task_metrics,
            // Ideation session commands
            commands::ideation_commands::create_ideation_session,
            commands::ideation_commands::create_cross_project_session,
            commands::ideation_commands::migrate_proposals,
            commands::ideation_commands::get_ideation_session,
            commands::ideation_commands::get_ideation_session_with_data,
            commands::ideation_commands::list_ideation_sessions,
            commands::ideation_commands::get_session_group_counts,
            commands::ideation_commands::list_sessions_by_group,
            commands::ideation_commands::archive_ideation_session,
            commands::ideation_commands::reopen_ideation_session,
            commands::ideation_commands::update_ideation_session_title,
            commands::ideation_commands::spawn_session_namer,
            commands::ideation_commands::get_child_sessions,
            // Task proposal commands
            commands::ideation_commands::create_task_proposal,
            commands::ideation_commands::get_task_proposal,
            commands::ideation_commands::list_session_proposals,
            commands::ideation_commands::update_task_proposal,
            commands::ideation_commands::delete_task_proposal,
            commands::ideation_commands::toggle_proposal_selection,
            commands::ideation_commands::set_proposal_selection,
            commands::ideation_commands::reorder_proposals,
            commands::ideation_commands::assess_proposal_priority,
            commands::ideation_commands::assess_all_priorities,
            // Dependency and apply commands
            commands::ideation_commands::remove_proposal_dependency,
            commands::ideation_commands::get_proposal_dependencies,
            commands::ideation_commands::get_proposal_dependents,
            commands::ideation_commands::analyze_dependencies,
            commands::ideation_commands::apply_proposals_to_kanban,
            commands::ideation_commands::get_task_blockers,
            commands::ideation_commands::get_blocked_tasks,
            // Chat message commands
            commands::ideation_commands::send_chat_message,
            commands::ideation_commands::get_session_messages,
            commands::ideation_commands::get_recent_session_messages,
            commands::ideation_commands::get_project_messages,
            commands::ideation_commands::get_task_messages,
            commands::ideation_commands::delete_chat_message,
            commands::ideation_commands::delete_session_messages,
            commands::ideation_commands::count_session_messages,
            // Orchestrator commands
            commands::ideation_commands::send_orchestrator_message,
            commands::ideation_commands::is_orchestrator_available,
            // Ideation settings commands
            commands::ideation_commands::get_ideation_settings,
            commands::ideation_commands::update_ideation_settings,
            // Agent lane settings commands
            commands::ideation_commands::get_agent_lane_settings,
            commands::ideation_commands::get_agent_harness_availability,
            commands::ideation_commands::get_ideation_harness_availability,
            commands::ideation_commands::update_agent_lane_settings,
            // Ideation effort commands
            commands::ideation_commands::get_ideation_effort_settings,
            commands::ideation_commands::update_ideation_effort_settings,
            // Ideation model commands
            commands::ideation_commands::get_ideation_model_settings,
            commands::ideation_commands::update_ideation_model_settings,
            // Ideation export/import commands
            commands::ideation_commands::export_ideation_session,
            commands::ideation_commands::import_ideation_session,
            // Workflow commands
            commands::workflow_commands::get_workflows,
            commands::workflow_commands::get_workflow,
            commands::workflow_commands::create_workflow,
            commands::workflow_commands::update_workflow,
            commands::workflow_commands::set_default_workflow,
            commands::workflow_commands::get_active_workflow_columns,
            commands::workflow_commands::get_builtin_workflows,
            commands::workflow_commands::seed_builtin_workflows,
            // Artifact commands
            commands::artifact_commands::get_artifacts,
            commands::artifact_commands::get_artifact,
            commands::artifact_commands::get_artifact_at_version,
            commands::artifact_commands::create_artifact,
            commands::artifact_commands::update_artifact,
            commands::artifact_commands::archive_artifact,
            commands::artifact_commands::get_artifacts_by_bucket,
            commands::artifact_commands::get_artifacts_by_task,
            commands::artifact_commands::get_team_artifacts_by_session,
            commands::artifact_commands::get_artifact_version_history,
            // Bucket commands
            commands::artifact_commands::get_buckets,
            commands::artifact_commands::create_bucket,
            commands::artifact_commands::get_system_buckets,
            // Artifact relation commands
            commands::artifact_commands::add_artifact_relation,
            commands::artifact_commands::get_artifact_relations,
            // Research commands
            commands::research_commands::start_research,
            commands::research_commands::pause_research,
            commands::research_commands::resume_research,
            commands::research_commands::stop_research,
            commands::research_commands::get_research_processes,
            commands::research_commands::get_research_process,
            commands::research_commands::get_research_presets,
            // Methodology commands
            commands::methodology_commands::get_methodologies,
            commands::methodology_commands::get_active_methodology,
            commands::methodology_commands::activate_methodology,
            commands::methodology_commands::deactivate_methodology,
            // Test data commands (for visual audits)
            commands::test_data_commands::seed_test_data,
            commands::test_data_commands::seed_visual_audit_data,
            commands::test_data_commands::clear_test_data,
            // Permission commands
            commands::permission_commands::resolve_permission_request,
            commands::permission_commands::get_pending_permissions,
            // Question commands (AskUserQuestion)
            commands::question_commands::resolve_user_question,
            commands::question_commands::get_pending_questions,
            // Task context commands
            commands::task_context_commands::get_task_context,
            commands::task_context_commands::get_artifact_full,
            commands::task_context_commands::get_artifact_version,
            commands::task_context_commands::get_related_artifacts,
            commands::task_context_commands::search_artifacts,
            // Unified chat commands (new API - consolidates context_chat + execution_chat)
            commands::unified_chat_commands::start_agent_conversation,
            commands::unified_chat_commands::switch_agent_conversation_mode,
            commands::unified_chat_commands::send_agent_message,
            commands::unified_chat_commands::queue_agent_message,
            commands::unified_chat_commands::get_queued_agent_messages,
            commands::unified_chat_commands::delete_queued_agent_message,
            commands::unified_chat_commands::list_agent_conversations,
            commands::unified_chat_commands::list_agent_conversations_page,
            commands::unified_chat_commands::get_agent_conversation,
            commands::unified_chat_commands::get_agent_conversation_messages_page,
            commands::unified_chat_commands::get_agent_conversation_workspace,
            commands::unified_chat_commands::list_agent_conversation_workspaces_by_project,
            commands::unified_chat_commands::list_agent_conversation_workspace_publication_events,
            commands::unified_chat_commands::get_agent_conversation_workspace_freshness,
            commands::unified_chat_commands::update_agent_conversation_workspace_from_base,
            commands::unified_chat_commands::publish_agent_conversation_workspace,
            commands::unified_chat_commands::create_agent_conversation,
            commands::unified_chat_commands::update_agent_conversation_title,
            commands::unified_chat_commands::archive_agent_conversation,
            commands::unified_chat_commands::restore_agent_conversation,
            commands::unified_chat_commands::append_agent_bridge_message,
            commands::unified_chat_commands::get_agent_run_status_unified,
            commands::unified_chat_commands::is_chat_service_available,
            commands::unified_chat_commands::stop_agent,
            commands::unified_chat_commands::is_agent_running,
            commands::agent_terminal_commands::open_agent_terminal,
            commands::agent_terminal_commands::write_agent_terminal,
            commands::agent_terminal_commands::resize_agent_terminal,
            commands::agent_terminal_commands::clear_agent_terminal,
            commands::agent_terminal_commands::restart_agent_terminal,
            commands::agent_terminal_commands::close_agent_terminal,
            // Chat attachment commands
            commands::chat_attachment_commands::upload_chat_attachment,
            commands::chat_attachment_commands::link_attachments_to_message,
            commands::chat_attachment_commands::list_conversation_attachments,
            commands::chat_attachment_commands::list_message_attachments,
            commands::chat_attachment_commands::delete_chat_attachment,
            // Activity event commands (pagination, filtering)
            commands::activity_commands::list_task_activity_events,
            commands::activity_commands::list_session_activity_events,
            commands::activity_commands::list_all_activity_events,
            commands::activity_commands::count_task_activity_events,
            commands::activity_commands::count_session_activity_events,
            // Diff commands
            commands::diff_commands::get_task_file_changes,
            commands::diff_commands::get_file_diff,
            commands::diff_commands::get_agent_conversation_workspace_file_changes,
            commands::diff_commands::get_agent_conversation_workspace_file_diff,
            commands::diff_commands::get_commit_file_changes,
            commands::diff_commands::get_commit_file_diff,
            commands::diff_commands::detect_merge_conflicts,
            commands::diff_commands::get_conflict_file_diff,
            // Git commands (Phase 66 - Per-task branch isolation)
            commands::git_commands::get_task_commits,
            commands::git_commands::get_task_diff_stats,
            commands::git_commands::resolve_merge_conflict,
            commands::git_commands::retry_merge,
            commands::git_commands::cleanup_task_branch,
            commands::git_commands::change_project_git_mode,
            // Plan branch commands (Phase 85 - Feature branch for plan groups)
            commands::plan_branch_commands::get_plan_branch,
            commands::plan_branch_commands::get_plan_branch_by_task_id,
            commands::plan_branch_commands::get_project_plan_branches,
            commands::plan_branch_commands::enable_feature_branch,
            // Plan commands (Active plan management)
            commands::plan_commands::get_active_plan,
            commands::plan_commands::set_active_plan,
            commands::plan_commands::get_active_execution_plan,
            commands::plan_commands::clear_active_plan,
            commands::plan_commands::list_plan_selector_candidates,
            // Team commands (agent teams collaboration)
            commands::team_commands::create_team,
            commands::team_commands::disband_team,
            commands::team_commands::get_team_status,
            commands::team_commands::send_team_message,
            commands::team_commands::send_teammate_message,
            commands::team_commands::stop_teammate,
            commands::team_commands::stop_team,
            commands::team_commands::get_team_messages,
            commands::team_commands::get_teammate_cost,
            commands::team_commands::get_team_history,
            // API key management commands (Tauri IPC — replaces HTTP fetch in settings UI)
            commands::api_key_commands::list_api_keys,
            commands::api_key_commands::create_api_key,
            commands::api_key_commands::revoke_api_key,
            commands::api_key_commands::rotate_api_key,
            commands::api_key_commands::update_api_key_projects,
            commands::api_key_commands::update_api_key_permissions,
            commands::api_key_commands::get_api_key_audit_log,
            commands::diagnostic_commands::get_agent_health,
            commands::diagnostic_commands::get_codex_cli_diagnostics,
            // UI feature flag commands
            commands::ui_commands::get_ui_feature_flags,
            // External MCP config commands
            commands::external_mcp_commands::get_external_mcp_config,
            commands::external_mcp_commands::update_external_mcp_config,
        ]
    };
}
